<?php

return [
    'name'       => 'Captcha',

    /*
    | Active captcha provider. Change it here or in .env (CAPTCHA_DRIVER=cloudflare):
    |
    |   local       image captcha generated by this module (see "presets" below)
    |   google      reCAPTCHA v2 checkbox      -> drivers.google
    |   cloudflare  Turnstile                  -> drivers.cloudflare
    |
    | @captcha / captcha_field() / CaptchaRule always use this driver, so switching
    | needs no change in your Blade views or controllers.
    */
    'driver'     => env('CAPTCHA_DRIVER', 'local'),

    // Turn the captcha off completely (check() always passes, fields render nothing).
    // Intended for local development / automated tests only - never enable in production.
    'disable'    => env('CAPTCHA_DISABLE', false),

    // (local driver) Cache store used for pending captcha. null = the default store.
    // Use a shared store (redis / database / file) when you run more than one server; "array" only works in tests.
    'store'      => env('CAPTCHA_CACHE_STORE'),

    // (local driver) How many new captcha ("new code" button) one IP may request per minute.
    'throttle'   => 60,

    // (local driver) Public URLs (relative to the site root). {token} is replaced with the captcha token.
    'routes'     => [
        'image'  => '/ajax/client-submitting/captcha/{token}',
        'reload' => '/ajax/client-submitting/captcha/load',
    ],

    /*
    | Settings of the remote providers.
    |
    | site_key    public key, printed in the page
    | secret_key  private key, ONLY used server side (keep it in .env)
    | api_url     browser script   (google: https://www.recaptcha.net/recaptcha/api.js works where google.com is filtered)
    | verify_url  server side check (google: https://www.recaptcha.net/recaptcha/api/siteverify)
    | timeout     seconds to wait for the provider. On timeout the captcha FAILS (it never lets a request through)
    | proxy       e.g. "http://127.0.0.1:8080" when this server cannot reach the provider directly
    | send_ip     send the visitor IP to the provider (improves its risk analysis)
    | hostnames   allowed hostnames the token may have been solved on, e.g. ['example.com'] ([] = do not check)
    | language    null = automatic, or "fa", "en" ...
    | widget      default look: theme (google: light|dark, cloudflare: auto|light|dark) and
    |             size (google: normal|compact, cloudflare: normal|compact|flexible)
    | presets     named looks: @captcha('compact') -> drivers.<name>.presets.compact
    |
    | Test keys (always pass / always fail, for local development only):
    |   Google      site 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI   secret 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
    |   Cloudflare  site 1x00000000000000000000AA                   secret 1x0000000000000000000000000000000AA
    */
    'drivers'    => [
        'google'     => [
            'site_key'   => env('CAPTCHA_GOOGLE_SITE_KEY'),
            'secret_key' => env('CAPTCHA_GOOGLE_SECRET_KEY'),
            'api_url'    => 'https://www.google.com/recaptcha/api.js',
            'verify_url' => 'https://www.google.com/recaptcha/api/siteverify',
            'timeout'    => 5,
            'proxy'      => env('CAPTCHA_HTTP_PROXY'),
            'send_ip'    => true,
            'hostnames'  => [],
            'language'   => null,
            'widget'     => ['theme' => 'light', 'size' => 'normal'],
            'presets'    => [
                'compact' => ['size' => 'compact'],
                'dark'    => ['theme' => 'dark'],
            ],
        ],
        'cloudflare' => [
            'site_key'   => env('CAPTCHA_CLOUDFLARE_SITE_KEY'),
            'secret_key' => env('CAPTCHA_CLOUDFLARE_SECRET_KEY'),
            'api_url'    => 'https://challenges.cloudflare.com/turnstile/v0/api.js',
            'verify_url' => 'https://challenges.cloudflare.com/turnstile/v0/siteverify',
            'timeout'    => 5,
            'proxy'      => env('CAPTCHA_HTTP_PROXY'),
            'send_ip'    => true,
            'hostnames'  => [],
            'language'   => null,
            'widget'     => ['theme' => 'auto', 'size' => 'normal'],
            'presets'    => [
                'compact'  => ['size' => 'compact'],
                'flexible' => ['size' => 'flexible'],
                'dark'     => ['theme' => 'dark'],
            ],
        ],
    ],

    // Alphabet of the local text captcha (visually confusing characters are left out on purpose).
    'characters' => ['2', '3', '4', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'j', 'm', 'n', 'p', 'q', 'r', 't', 'u', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'M', 'N', 'P', 'Q', 'R', 'T', 'U', 'X', 'Y', 'Z'],

    /*
    | (local driver) Presets. Use them with @captcha('flat'), Captcha::local()->make('flat') or new CaptchaRule('flat').
    |
    | Available keys (all optional):
    | length, width, height, quality, math, sensitive, expire (seconds), angle, lines, lineWidth,
    | lineColor, noise, bgImage, bgColor, fill, fontColors, contrast, sharpen, blur, invert,
    | marginTop, textLeftPadding, characters
    */
    'presets'    => [
        'default' => [
            'length'  => 5,
            'width'   => 120,
            'height'  => 36,
            'quality' => 90,
            'math'    => false,
            'expire'  => 180,
        ],
        'math'    => [
            'width'   => 120,
            'height'  => 36,
            'quality' => 90,
            'math'    => true,
        ],
        'flat'    => [
            'length'     => 6,
            'width'      => 160,
            'height'     => 46,
            'quality'    => 90,
            'lines'      => 6,
            'bgImage'    => false,
            'bgColor'    => '#ecf2f4',
            'fontColors' => ['#2c3e50', '#c0392b', '#16a085', '#c0392b', '#8e44ad', '#303f9f', '#f57c00', '#795548'],
            'contrast'   => -5,
        ],
        'mini'    => [
            'length' => 3,
            'width'  => 60,
            'height' => 32,
        ],
        'inverse' => [
            'length'    => 5,
            'width'     => 120,
            'height'    => 36,
            'quality'   => 90,
            'sensitive' => true,
            'angle'     => 12,
            'sharpen'   => 10,
            'blur'      => 2,
            'invert'    => true,
            'contrast'  => -5,
        ],
        'custom'  => [
            'length'     => 5,
            'width'      => 120,
            'height'     => 36,
            'quality'    => 90,
            'math'       => false,
            'expire'     => 180,
            'fontColors' => ['#3f0211', '#3e023f', '#02083f', '#023f13', '#6c7c00', '#5b1f04'],
        ],
    ],
];
