<?php

namespace Lareon\Modules\Captcha\App\Services;

use Closure;
use Illuminate\Contracts\Config\Repository as ConfigRepository;
use Illuminate\Support\HtmlString;
use InvalidArgumentException;
use LogicException;
use Lareon\Modules\Captcha\App\Contracts\CaptchaDriver;

/**
 * Picks the captcha provider from config('captcha.driver'):
 *
 *   local       image captcha generated by this module
 *   google      Google reCAPTCHA v2
 *   cloudflare  Cloudflare Turnstile
 *
 * Forms and validation only talk to the manager, so switching provider is a
 * one line config / .env change (CAPTCHA_DRIVER=cloudflare).
 */
class CaptchaManager
{
    private const NAME_PATTERN = '/^[a-z][a-z0-9_-]{0,31}$/';

    /** @var array<string, Closure(): CaptchaDriver> */
    private array $creators = [];

    /** @var array<string, CaptchaDriver> */
    private array $drivers = [];

    public function __construct(private readonly ConfigRepository $config)
    {
    }

    /**
     * Register (or replace) a driver. Use it to add your own provider (hCaptcha, ...).
     *
     * @param Closure(): CaptchaDriver $creator
     */
    public function extend(string $name, Closure $creator): static
    {
        $this->creators[$name] = $creator;
        unset($this->drivers[$name]);

        return $this;
    }

    public function defaultDriver(): string
    {
        return (string)$this->cfg('driver', 'local');
    }

    /**
     * @throws InvalidArgumentException when the driver is unknown
     */
    public function driver(?string $name = null): CaptchaDriver
    {
        $name ??= $this->defaultDriver();

        if (isset($this->drivers[$name])) {
            return $this->drivers[$name];
        }

        if (!preg_match(self::NAME_PATTERN, $name) || !isset($this->creators[$name])) {
            throw new InvalidArgumentException(sprintf(
                'Captcha driver [%s] is not supported. Available drivers: %s.',
                preg_match(self::NAME_PATTERN, $name) ? $name : '(invalid name)',
                implode(', ', array_keys($this->creators))
            ));
        }

        return $this->drivers[$name] = ($this->creators[$name])();
    }

    /**
     * The built-in image captcha (needed for make() / image() / discard() and for SPA endpoints).
     */
    public function local(): CaptchaService
    {
        $driver = $this->driver('local');

        if (!$driver instanceof CaptchaService) {
            throw new LogicException('The "local" captcha driver must be a CaptchaService.');
        }

        return $driver;
    }

    /**
     * One captcha block of the active driver, followed by the script it needs
     * (printed only once per request).
     *
     * @param array $options name, id, class, widget[] and:
     *                       driver  use another driver for this field only
     *                       script  false = do not print the script here (use captcha_script() yourself)
     *                       nonce   CSP nonce for the script
     */
    public function field(string $preset = 'default', array $options = []): HtmlString
    {
        if ($this->isDisabled()) {
            return new HtmlString('');
        }

        $driver = $this->driver(isset($options['driver']) ? (string)$options['driver'] : null);
        $withScript = (bool)($options['script'] ?? true);
        $nonce = isset($options['nonce']) ? (string)$options['nonce'] : null;

        unset($options['driver'], $options['script'], $options['nonce']);

        $html = (string)$driver->field($preset, $options);

        if ($withScript) {
            $html .= (string)$driver->script($nonce);
        }

        return new HtmlString($html);
    }

    /**
     * Script of the active driver (only needed with 'script' => false).
     */
    public function script(?string $nonce = null, ?string $driver = null): HtmlString
    {
        return $this->isDisabled() ? new HtmlString('') : $this->driver($driver)->script($nonce);
    }

    /**
     * Validate ONE captcha with the active driver (or the given one).
     */
    public function check(?string $answer, ?string $token = null, ?string $preset = null, ?string $driver = null): bool
    {
        if ($this->isDisabled()) {
            return true;
        }

        return $this->driver($driver)->check($answer, $token, $preset);
    }

    /**
     * Public info about the active driver for SPAs / mobile apps.
     *
     * @return array<string, mixed>
     */
    public function clientConfig(?string $driver = null): array
    {
        return ['disabled' => $this->isDisabled()] + $this->driver($driver)->clientConfig();
    }

    public function isDisabled(): bool
    {
        return (bool)$this->cfg('disable', false);
    }

    /**
     * Read a config value from "modules.captcha.*" with fallback to "captcha.*".
     */
    private function cfg(string $key, mixed $default = null): mixed
    {
        foreach (['modules.captcha.', 'captcha.'] as $prefix) {
            if ($this->config->has($prefix . $key)) {
                return $this->config->get($prefix . $key);
            }
        }

        return $default;
    }
}
