<x-lareon::admin-layout>
    @section('title', __('robot.txt'))
    @section('description', __("a log file is a record of events, activities, or errors generated by the application or server for monitoring and debugging purposes"))

    <section class="mb-6" x-data="{ dark: true, wrap: true }">
        <div class="grid items-center grid-cols-2 mb-2">
            <div class="flex items-center justify-end">
                <button type="button" @click="dark = !dark" class="px-3 py-1 rounded border text-sm">
                    <span x-text="dark ? '☀️ Light' : '🌙 Dark'"></span>
                </button>
            </div>
        </div>
        <form action="{{route('admin.seo.robot.update')}}" method="POST">
            @csrf
            @method('PATCH')
            <textarea name="content" dir="ltr" class="input font-semibold w-full max-h-screen overflow-auto transition-colors duration-300" :class="dark ? 'bg-zinc-900 text-gray-300': 'bg-slate-50 text-gray-900'" rows="12">{!! $content !!}</textarea>

            <div class="mt-6">
                <x-lareon::buttons.nav class="w-24" :fullWidth="false" type="submit" role="submit" color="create">
                    {{ __('update')}}
                </x-lareon::buttons.nav>
            </div>
        </form>
    </section>

</x-lareon::admin-layout>
