<x-lareon::admin-layout>
    @section('title', __('robot.txt'))
    @section('description', __("a log file is a record of events, activities, or errors generated by the application or server for monitoring and debugging purposes"))

    <section class="mb-6" x-data="{ dark: true, wrap: true }">
        <div class="grid items-center grid-cols-2 mb-2">
            <div class="flex items-center justify-end">
                <button type="button" @click="dark = !dark" class="px-3 py-1 rounded border text-sm">
                    <span x-text="dark ? '☀️ Light' : '🌙 Dark'"></span>
                </button>
                <button type="button" @click="wrap = !wrap" class="px-3 py-1 rounded border text-sm">
                    <span x-text="wrap ? '➡️ unwrap' : '↩️  wrap'"></span>
                </button>
            </div>
        </div>
        <textarea name="content" dir="ltr" class="font-semibold p-6 rounded-lg w-full max-h-screen overflow-auto transition-colors duration-300"
             :class="dark ? 'bg-zinc-900 text-gray-300'    : 'bg-slate-50 text-gray-900 border'">
            <pre :class="wrap ? 'whitespace-pre-wrap'    : ''">{!! $content !!}</pre>
        </textarea>

    </section>

</x-lareon::admin-layout>
